export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ADMIN_SYSTEME = 'ROLE_ADMIN_SYSTEME',
  ADMIN_COMMERCIAL = 'ROLE_ADMIN_COMMERCIAL',
  COMMERCIAL = 'ROLE_COMMERCIAL',
  MAGASINIER = 'ROLE_MAGASINIER',
  CLIENT = 'ROLE_CLIENT',
  RESP_PV = 'ROLE_RESP_PV',
  VENDEUR = 'ROLE_VENDEUR',
  CHEF_PARC = 'ROLE_CHEF_PARC',
}
